[env]
VCPKGRS_DYNAMIC = "1"
RUSTFLAGS = "-C target-feature=+crt-static"

[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]

[build]
rustflags = ["-C", "link-arg=/NODEFAULTLIB:libcmt"] 